### ISSUE TITLE
其他的数据如何导出

### ISSUE THREAD

**Issue by dian-yu-luo** [busiyiworld/maimemo-export#1]
能够导出其他的数据比如,例句和助记,或者请问有没有其他的什么平台能够提供这些数据

**Comment by cquestor** [comment]
我记得这些数据虽然都在数据库里，但都经过了加密，没法看

**Comment by dian-yu-luo** [comment]
应该不是,因为如果我不联网,这些数据也不能获得,所以应该是储存在服务器端的

**Comment by cquestor** [comment]
> 应该不是,因为如果我不联网,这些数据也不能获得,所以应该是储存在服务器端的

emmm，您使用的是最新版的app吗？我这边断网是也可以正常使用的，只有语音文件需要请求，其他助记，句意什么的一切正常
